name: book_swap_app
description: BookSwap starter
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  uuid: ^3.0.7
  flutter_bloc: ^8.1.2   # or the latest version
  equatable: ^2.0.5 
  firebase_core: ^2.22.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
